apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir 
spec:
  containers:
  - name: nginx # 컨테이너 이름
    image: nginx # 이미지 이름
    volumeMounts: # 컨테이너 안에서 마운트 실행
    - name: shared-storage # volumes 의 이름을 그대로 사용
      mountPath: /data/shared
  volumes:
  - name: shared-storage
    emptyDir: {} # 파드 내에 저장소를 생성