apiVersion: apps/v1 # 디플로이먼트나 파드는 실행되어야 하므로 앞에 app 이 붙음
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql # metadata 의 이름을 그대로 사용
  strategy:
    type: Recreate # 업데이트 전략으로 생략하면 롤링(Rolling)이 적용됨
    # 데이터베이스는 롤링을 사용하지 않는 대표적인 컨테이너
  template:
    metadata:
      labels:
        app: mysql
    spec: 
    # 디플로이먼트나 파드는 spec > template 안에 다시 spec 을 만들어서
    # 컨테이너를 생성
      containers:
      - image: mysql:8.0.29
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password # value 에 패스워드를 입력
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pvc-storage # volumes 와 동일한 이름
          mountPath: var/mysql # 디렉토리 설정
      volumes:
      - name: mysql-pvc-storage
        persistentVolumeClaim:
          claimName: mysql-pvc # pvc.yaml 파일의 이름이 와야 함