apiVersion: v1
kind: PersistentVolumeClaim # 영구 볼륨 클레임 생성
metadata:
  name: mysql-pvc
  # label 은 필요하지 않음

spec:
  storageClassName: manual 
  accessModes: # pv 와 동일
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # 볼륨보다 작은 크기면 상관 없음


